//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usertable
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string RepassWord { get; set; }
        public string passWord { get; set; }
        public Nullable<int> userRoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Usertable Usertable1 { get; set; }
        public virtual Usertable Usertable2 { get; set; }
        public virtual Usertable Usertable11 { get; set; }
        public virtual Usertable Usertable3 { get; set; }
    }
}
